name: third_flow 

on:
  workflow_run:
    workflows:
      - second_flow 
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print hello world
        run: echo "third flow"